# Workflow pour construire et déployer un site Vite sur GitHub Pages
name: Deploy Vite site to Pages

on:
  # Se déclenche sur les push vers la branche "main"
  push:
    branches: ["main"]

  # Permet de le lancer manuellement depuis l'onglet Actions
  workflow_dispatch:

# Autorisations pour le GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Permet un seul déploiement concurrent
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Tâche de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # ---------------------------------------------------- #
      # 👇 ÉTAPES AJOUTÉES : CONFIGURATION ET BUILD
      # ---------------------------------------------------- #
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Utilise une version LTS de Node
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # Exécute le script "build" de votre package.json
      # ---------------------------------------------------- #
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # ---------------------------------------------------- #
          # 👇 MODIFICATION CLÉ : Utiliser le dossier 'dist'
          # ---------------------------------------------------- #
          path: './dist' # Au lieu de '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
